CREATE DATABASE IF NOT EXISTS devops_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS devops_message CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS devops_log CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
